using Microsoft.EntityFrameworkCore;
using ProductsAPI.Models;

namespace ProductsAPI.Data;

public class ProductContext : DbContext
{
    public ProductContext(DbContextOptions<ProductContext> options) : base(options)
    {
    }

    public DbSet<Product> Products { get; set; } = null!;
    public DbSet<Category> Categories { get; set; } = null!;
    public DbSet<Supplier> Suppliers { get; set; } = null!;
    public DbSet<ProductSupplier> ProductSuppliers { get; set; } = null!;


    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        ConfigureProductModel(modelBuilder);
        ConfigureCategoryModel(modelBuilder);
        ConfigureSupplierModel(modelBuilder);
        ConfigureProductSupplierModel(modelBuilder);

        SeedProductData(modelBuilder);
    }

    private void ConfigureProductModel(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Product>(entity =>
        {
            entity.HasKey(p => p.Id);
            entity.Property(p => p.Id).ValueGeneratedOnAdd(); // Ensuring the ID is autogenerated
            entity.Property(p => p.Name).IsRequired().HasMaxLength(100);
            entity.Property(p => p.Description).IsRequired().HasMaxLength(500);
            entity.Property(p => p.Price).HasColumnType("decimal(18,2)").IsRequired();
            
            // Handling the LastUpdated property to auto-generate on add or update
            entity.Property(p => p.LastUpdated).HasColumnType("datetime2").IsRequired()
                .HasDefaultValueSql("GETDATE()");

            // Configuring the relationship with Category
            entity.HasOne(p => p.Category)
                .WithMany(c => c.Products)
                .HasForeignKey(p => p.CategoryId)
                .IsRequired(); // Ensuring the foreign key to Category is not nullable

            entity.Property(p => p.StockLevel).IsRequired(); 
        });
    }

    private void ConfigureCategoryModel(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Category>(entity =>
        {
            entity.HasKey(c => c.Id);
            entity.Property(c => c.Id).ValueGeneratedOnAdd();
            entity.Property(c => c.Name).IsRequired().HasMaxLength(100);
        });
    }

    private void ConfigureSupplierModel(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Supplier>(entity =>
        {
            entity.HasKey(s => s.Id);
            entity.Property(s => s.Name).IsRequired().HasMaxLength(100);
            entity.Property(s => s.Email).IsRequired().HasMaxLength(100);
        });
    }

    private void ConfigureProductSupplierModel(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ProductSupplier>(entity =>
        {
            entity.HasKey(ps => new { ps.ProductId, ps.SupplierId });            
            entity.HasOne(ps => ps.Product).WithMany(p => p.ProductSuppliers).HasForeignKey(ps => ps.ProductId);
            entity.HasOne(ps => ps.Supplier).WithMany(s => s.ProductSuppliers).HasForeignKey(ps => ps.SupplierId);
        });
    }

    private void SeedProductData(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Category>().HasData(
            new Category { Id = 1, Name = "Clothing" },
            new Category { Id = 2, Name = "Footwear" },
            new Category { Id = 3, Name = "Accessories" }
        );
        
        modelBuilder.Entity<Product>().HasData(
            new Product { Id = 1, Name = "T-shirt", Description = "Cotton white", Price = 15.99m, StockLevel = 2, CategoryId = 1 },
            new Product { Id = 2, Name = "Running Shoes", Description = "Best for marathons", Price = 50.00m, StockLevel = 7, CategoryId = 2 },
            new Product { Id = 3, Name = "Baseball Cap", Description = "Adjustable size", Price = 12.50m, StockLevel = 0, CategoryId = 3}
        );

        modelBuilder.Entity<Supplier>().HasData(
            new Supplier { Id = 1, Name = "Global Textiles Inc", Email = "contact@globaltextiles.com" },
            new Supplier { Id = 2, Name = "Footwear Co.", Email = "info@footwearco.com" },
            new Supplier { Id = 3, Name = "Headgear Ltd.", Email = "support@headgearltd.com" }
        );

        modelBuilder.Entity<ProductSupplier>().HasData(
            new ProductSupplier { Id = 1, ProductId = 1, SupplierId = 1 },
            new ProductSupplier { Id = 2, ProductId = 2, SupplierId = 2 },
            new ProductSupplier { Id = 3, ProductId = 3, SupplierId = 3 },
            new ProductSupplier { Id = 4, ProductId = 1, SupplierId = 3 } 
        );
    }
}
