// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductsAPI.Data;

#nullable disable

namespace ProductsAPI.Data.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20241213044139_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("ProductsAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("StockStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Cotton white",
                            LastUpdated = new DateTime(2024, 12, 13, 4, 41, 38, 933, DateTimeKind.Utc).AddTicks(3343),
                            Name = "T-shirt",
                            Price = 15.99m,
                            StockStatus = "In Stock"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Best for marathons",
                            LastUpdated = new DateTime(2024, 12, 13, 4, 41, 38, 933, DateTimeKind.Utc).AddTicks(3345),
                            Name = "Running Shoes",
                            Price = 50.00m,
                            StockStatus = "In Stock"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Adjustable size",
                            LastUpdated = new DateTime(2024, 12, 13, 4, 41, 38, 933, DateTimeKind.Utc).AddTicks(3346),
                            Name = "Baseball Cap",
                            Price = 12.50m,
                            StockStatus = "Out of Stock"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
