// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductsAPI.Data;

#nullable disable

namespace ProductsAPI.Data.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20241223035254_AdjustIdAutoGeneration")]
    partial class AdjustIdAutoGeneration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductsAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("StockStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Cotton white",
                            LastUpdated = new DateTime(2024, 12, 23, 3, 52, 53, 844, DateTimeKind.Utc).AddTicks(9859),
                            Name = "T-shirt",
                            Price = 15.99m,
                            StockStatus = "In Stock"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Best for marathons",
                            LastUpdated = new DateTime(2024, 12, 23, 3, 52, 53, 844, DateTimeKind.Utc).AddTicks(9865),
                            Name = "Running Shoes",
                            Price = 50.00m,
                            StockStatus = "In Stock"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Adjustable size",
                            LastUpdated = new DateTime(2024, 12, 23, 3, 52, 53, 844, DateTimeKind.Utc).AddTicks(9867),
                            Name = "Baseball Cap",
                            Price = 12.50m,
                            StockStatus = "Out of Stock"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
