name: Deploy to Azure

on:
    push:
    workflow_dispatch:

env:
  PROJECT_PATH: ./ProductsAPI
  PUBLISH_PATH: ./myapp

jobs:
    build_and_test:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
    
          - name: Set up .NET Core
            uses: actions/setup-dotnet@v4
            with:
              dotnet-version: '8.x'

          - name: Install Entity Framework Core CLI
            run: dotnet tool install --global dotnet-ef

          - name: Add .NET tools to PATH
            # On GitHub-hosted runners, you must add the global tools directory to PATH.
            run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
    
          - name: Build with dotnet
            run: dotnet build ${{ env.PROJECT_PATH }}/ProductsAPI.csproj --configuration Release
    
          - name: Run unit tests
            run: dotnet test ${{ env.PROJECT_PATH }}/ProductsAPI.csproj --configuration Release --no-build --logger "trx;LogFileName=test_results.xml"

          - name: Publish App
            run: dotnet publish ${{ env.PROJECT_PATH }}/ProductsAPI.csproj -c Release -o ${{ env.PUBLISH_PATH }}


          - name: Generate Migration Script
            run: dotnet ef migrations script --idempotent --output ./migrations.sql --project ${{ env.PROJECT_PATH }}
            env:
              ASPNETCORE_ENVIRONMENT: Production
              ConnectionStrings__DefaultConnection: ${{ secrets.DATABASE_CONNECTION_STRING }}

          - name: Upload Migration Script
            uses: actions/upload-artifact@v3
            with:
              name: Migration-Script
              path: ./migrations.sql
            

          - name: Upload artifact
            uses: actions/upload-artifact@v4
            with:
              name: .net-app
              path: ${{ env.PUBLISH_PATH }}

    deploy_to_staging:
        if: ${{ github.ref == 'refs/heads/dev' }}
        environment: 
            name: Staging
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
        runs-on: ubuntu-latest
        needs: build_and_test
        permissions:
            contents: read
            id-token: write #This is required for requesting the JWT
        
        steps:            
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                  name: .net-app
                  path: ${{ env.PUBLISH_PATH }}
        
            - name: Deploy to Staging Slot
              uses: azure/webapps-deploy@v3
              with:
                  app-name: 'thamco-productsapi'
                  slot-name: 'Staging'
                  publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
                  package: ${{ env.PUBLISH_PATH }}

                  
    deploy_to_production:
        if: ${{ github.ref == 'refs/heads/main' }}
        environment: 
            name: Production
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
        runs-on: ubuntu-latest
        needs: build_and_test
        permissions:
            contents: read
            id-token: write #This is required for requesting the JWT

        steps:
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                  name: .net-app
                  path: ${{ env.PUBLISH_PATH }}

              # Download the migrations.sql script
            - name: Download Migration Script
              uses: actions/download-artifact@v4
              with:
                name: Migration-Script
                path: ./migrations.sql
              
              # Apply the migration script using Azure SQL Action
            - name: Apply Migration Script to Production
              uses: azure/sql-action@v2
              with:
                connection-string: ${{ secrets.DATABASE_CONNECTION_STRING }}
                sql-file: './migrations.sql'
    
            - name: Deploy to Production
              uses: azure/webapps-deploy@v3
              with:
                  app-name: 'ThAmCo-ProductsAPI'
                  publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
                  package: ${{ env.PUBLISH_PATH }}
