name: Deploy to Azure

on:
    push:
    workflow_dispatch:

env:
  PROJECT_PATH: ./ProductsAPI
  PUBLISH_PATH: ./myapp

jobs:
    deploy_to_staging:
        if: ${{ github.ref == 'refs/heads/dev' }}
        environment: 
            name: Staging
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write #This is required for requesting the JWT
        
        steps:
            - uses: actions/checkout@v4

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: .net-app
                  path: ${{ env.PUBLISH_PATH }}
            
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                  name: .net-app
                  path: ${{ env.PUBLISH_PATH }}
        
            - name: Deploy to Staging Slot
              uses: azure/webapps-deploy@v3
              with:
                  app-name: 'thamco-productsapi'
                  slot-name: 'Staging'
                  publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
                  package: ${{ env.PUBLISH_PATH }}

    deploy_to_production:
        if: ${{ github.ref == 'refs/heads/main' }}
        environment: 
            name: Staging
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write #This is required for requesting the JWT

        steps:
            - uses: actions/checkout@v4
            
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: .net-app
                path: ${{ env.PUBLISH_PATH }}

            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                  name: .net-app
                  path: ${{ env.PUBLISH_PATH }}
    
            - name: Deploy to Production
              uses: azure/webapps-deploy@v3
              with:
                  app-name: 'ThAmCo-ProductsAPI'
                  publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
                  package: ${{ env.PUBLISH_PATH }}